version: '2'

services:

  external-drive:
    build: .
    privileged: true
    environment: 
      # devuuid|container_name,container_name;devuuid|container_name,container_name
      MOUNT_START_CONTAINERS: "BC48-5469|abc,456;ANOTHER-UUID|def,ghi;ANOTHER-UUID,+REQUIRED-UUID|jkl,mno"
      UNMOUNT_STOP_CONTAINERS: "BC48-5469|abc,456;ANOTHER-UUID|def,ghi;ANOTHER-UUID,+REQUIRED-UUID|jkl,mno"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # rshared: To make the the mount operations also propagate to original mounts
      - /mnt/external-drive:/mnt:rshared